wrong_option=true
driverlist=org.postgresql.Driver
deregisterdrivers=true
appender=com.p6spy.engine.spy.appender.StdoutLogger
logMessageFormat=com.hyunsoft.stock8888.common.util.SelectQueryExtractor
logfile=
filter=true
sqlexpression=(?is)^\\s*(with).*