apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yaml: |
    multitenancy_enabled: false

    server:
      http_listen_port: 3200

    # 1. 메트릭 제너레이터 활성화
    metrics_generator_enabled: true

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    # 2. 메트릭 제너레이터 상세 설정
    metrics_generator:
      storage:
        path: /var/tempo/wal
        remote_write:
          - url: http://prometheus:9090/api/v1/write  # Prometheus 주소에 맞게 수정
            send_exemplars: true
      
      processor:
        service_graphs:
          enabled: true
        span_metrics:
          enabled: true
          latency_histogram_buckets: [100ms, 250ms, 500ms, 1s, 2.5s, 5s, 10s]

    storage:
      trace:
        backend: local                     # S3 등 외부 스토리지를 사용한다면 수정 필요
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
